name: TissueBox
description: A mobile phone game made by Flutter.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flame: "0.10.2"
  shared_preferences: ^0.5.1+2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/c
    - assets/images/b
    - assets/images/0
    - assets/images/1
    - assets/images/2
    - assets/images/3
    - assets/images/4
    - assets/images/5
    - assets/images/6
    - assets/images/t
    - assets/audio/s.mp3
    - assets/audio/d.mp3
    - assets/audio/t.mp3
    - assets/audio/tk.mp3
    - assets/audio/a.mp3
  fonts:
    - family: NS
      fonts:
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700